# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3653c55bc88cf7f167f81ff63864dd51a3be10d92b49c7045bf75424153723950854a92a08564d823cd354529765f97a3827bbb65caf21d3a190ac8324205ebb

test:
  secret_key_base: a37038733dd60117fb74556a38a26c73fb489db00c93870d6e8592b5c23dcb0f6c103d316658bb085450bfc690fb0e19157a7055de0a78dd212f438af98538fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= Settings.SECRET_KEY_BASE %>
